GUI Fixes
Fidentis/Analyst pull request #27
Opened 2017-05-19 15:13 UTC by katush

-Small gui layout fixes
-Histogram tresholding fix
-Added spinner to trasparency setting

2017-05-20 19:59 UTC, ZueFe requested changes
value transparency slidera by mala byt ulozena v datovom modely pre dany projekt, kvoli nastaveniu hodnot pri prepinani tabov, a mala by byt nastavovana v metode setConfiguration() + default hodnota v datovom modele by mala byt nastavovana v odpovedajucej triede z packagu cz.fidentis.gui.guisetup

vsade kde je transparencySlider.getValue() by sa mala pouzivat hodnota z datoveho modulu

2017-05-20 20:04 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/PairComparisonPanel.java
> +            transpSpinner.setValue((int)transparencySlider.getValue());
vid. review, je potrebne nastavovat hodnotu transparency v datovom module, sa mi ale vidi, ze momentalny kod v developmente vyzera trocha inak, ako to co bolo prepisane podla diffu

2017-05-20 20:05 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/PairComparisonPanel.java
> +            transparencySlider.setValue((int)transpSpinner.getValue());
to iste ako v slidery

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonConfiguration.java
> +        color[3] = primSolidCheckbox.isSelected() ? 1 : transparencySlider.getValue() / (float) 100;
value z datoveho modulu, rovnako is selected

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonConfiguration.java
> +        color2[3] = secSolidCheckbox.isSelected() ? 1 : transparencySlider.getValue() / (float) 100;
value z datoveho modulu,rovnako is selected

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonResults.java
> +        color[3] = primSolidCheckbox.isSelected() ? 1 : transparencySlider.getValue() / (float) 100;
value z datoveho modulu, rovnako is selected

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonResults.java
> +        color2[3] = secSolidCheckbox.isSelected() ? 1 : transparencySlider.getValue() / (float) 100;
value z datoveho modulu, rovnako is selected

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/ViewerPanel_2Faces.java
> +        if (canvasNumber == 0) {
+1 za style 👍 :)

2017-05-20 20:38 UTC, ZueFe commented on Visualisation/src/cz/fidentis/visualisation/histogram/histogramPanel.java
> +        }
just a wild suggestion, konstanty? len pre zaujimavost, co presne je v tomto pripade 5?

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_batch/BatchComparisonResults.java
> +             tc.getProject().getSelectedBatchComparison().getHDinfo().setIndicesForNormals(tc.getProject().getSelectedBatchComparison().getHDinfo().getGraph().indicesFordDensityNormals(density.getVal
tc.getProject().getSelectedBatchComparison() by sa malo dat nahradit volanim getContext()

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_one_to_many/OneToManyComparisonResults.java
> +            ModelLoader l = new ModelLoader();
ModelLoader by mal byt rieseny cez singelton (popravde volat konstruktor by nemalo byt mozne), mas mergnutu spravnu verziu kodu?

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_one_to_many/OneToManyComparisonResults.java
> +            ModelLoader l = new ModelLoader();
to iste ako predtym

2017-05-20 20:38 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_one_to_many/OneToManyComparisonResults.java
> +   /*  private void setupVisualizationControls() {
pokial sa to uz nepouziva, tak to rovno zmaz

2017-05-22 10:52 UTC, katush commented on Visualisation/src/cz/fidentis/visualisation/histogram/histogramPanel.java
> +        }
padding od okraju canvasu (resp. polometer toho maleho cerneho trojuholnicka, aby nemohol vyletiet mimo canvas)

2017-05-22 10:53 UTC, katush commented on GUI/src/cz/fidentis/gui/PairComparisonPanel.java
> +            transpSpinner.setValue((int)transparencySlider.getValue());
spravne!

2017-06-26 10:39 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/PairComparisonPanel.java
>              setMinThreshValue();
nie som si uplne ista, ci to chapem spravne, ale je tu dovod, preco sa hodnoty v setMinThreshValue a setMaxThreshValue sortuju vzdy ked sa zmeni hodnota v spinnery/slidery?

2017-06-26 10:39 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_batch/BatchComparisonResults.java
> +        if (histogram1.isMaxSliderSelected()) {
pridaj komentare, prosim ta, neda sa velmi vyznat v tom co presne sa tu deje

2017-06-26 10:39 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_one_to_many/OneToManyComparisonResults.java
> +        if (histogram1.isMaxSliderSelected()) {
podobne ako v batchi, moze naraz nastat situacia kedy je max a min slider selected? potrebujes vzdy volat  min/max tresh value na riadku 1923 (sice to nebezi vo viacerych vlaknach, ak si spravne pamatam, ale je fajn mat tu hodnotu zafixovanu, pre pripad)

2017-06-26 10:39 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonResults.java
> +                + getContext().getUpperHDTreshold() * 100 + "% treshold",
y u hate my string style? :)

2017-06-26 10:39 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonResults.java
> +        if (histogram1.isMaxSliderSelected()) {
toto iste tu vidim uz 3x

2017-06-26 10:39 UTC, ZueFe commented on Visualisation/src/cz/fidentis/visualisation/histogram/histogramPanel.java
> +        }
sprav z toho konstantu :)

2017-06-26 10:39 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_batch/BatchComparisonResults.java
> +        plotsDrawingPanelBatchNumerical1.setPeakStrength(jSlider4.getValue() / (float) 10);
(float)? jSlider4, daj tomu prosimta nejake rozumne meno

2017-06-26 10:39 UTC, ZueFe commented on Renderer/src/cz/fidentis/renderer/shaders/ColormapFS.glsl
> +discard;
hum?

2017-06-26 10:39 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonResults.java
> +    public void adjustThresholds(){
asi by som vela chcela, aby tato metoda existovala len 1x pre vsetky 3 mody co?

2017-06-27 12:55 UTC, ZueFe commented on Renderer/src/cz/fidentis/renderer/ComparisonGLEventListener.java
> +                    gl.glBegin(GL_LINES);
da sa glBegin/end vyhodit von z cyklu? dost to spomaluje program pokial sa to furt prepina

2017-06-29 11:43 UTC, katush commented on GUI/src/cz/fidentis/gui/PairComparisonPanel.java
>              setMinThreshValue();
No.. pokial si ich niekde mozem vytiahnut sortovane tak ich asi nemusim sortovat vzdy ale inak hej. Musia byt sortovane, inak nespocitas kolko percent ma byt oseknutych (ak je oseknutie dane hodnotov z histogramu) alebo naopak hodnotu oseknutia pre histogram (ak je threshold dany percentom)

2017-06-29 11:45 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/PairComparisonPanel.java
>              setMinThreshValue();
nestaci ich zosortovat raz a potom si to niekde ulozit?

2017-06-29 11:45 UTC, katush commented on Renderer/src/cz/fidentis/renderer/ComparisonGLEventListener.java
> +                    gl.glBegin(GL_LINES);
Nastudujem, ale niektore nastavenia opengl nemozu byt v begin-end bloku

2017-06-29 11:47 UTC, katush commented on Renderer/src/cz/fidentis/renderer/shaders/ColormapFS.glsl
> +discard;
Aby sa  zbytocne nevykreslova fragment - on sa iba storuje do textury, ktora sa potom pouzije v dalsom shadri, netreba ho zapisovat i do frame buffru

2017-06-29 11:48 UTC, katush commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonResults.java
> +                + getContext().getUpperHDTreshold() * 100 + "% treshold",
Autoformat asi...

2017-06-29 12:25 UTC, katush commented on GUI/src/cz/fidentis/gui/comparison_two_faces/PairComparisonConfiguration.java
> +        color2[3] = secSolidCheckbox.isSelected() ? 1 : transparencySlider.getValue() / (float) 100;
ty checkboxy a slider ok... ale faby sa na tomto mieste prave do datoveho modulu ukladaju

2017-06-29 12:35 UTC, katush commented on GUI/src/cz/fidentis/gui/PairComparisonPanel.java
>              setMinThreshValue();
Done

2017-06-29 12:40 UTC, merged