Development
Fidentis/Analyst pull request #48
Opened 2017-10-07 11:15 UTC by RastislavStefanko

+added landmark analysis, +added landmark training model

2017-10-09 14:40 UTC, ZueFe requested changes
Niektore casti kodu, tak ako su teraz, nie su funkcne

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkActionDialogueTopComponent.java
> +        //setToolTipText(Bundle.HINT_LandmarkActionDialogueTopComponent());
odstran zakomentovany kod, ked ho nikde nepouzivas

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkActionDialogueTopComponent.java
> +    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
pomenuj to tlacidlo nejak rozumne, vo vseobecnosti pomenuj tlacidla, labely, text fields etc.

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkActionDialogueTopComponent.java
> +        // TODO add your handling code here:
TODO komentare by bolo dobre poriesit predtym, ake commitnes kod, vymaz pokial su nepodstatne, vyries pokial su podstatne, pokial sa nedaju vyriesit, tak aspon napis, kedy ich bude mozne vyriesit.

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkActionDialogueTopComponent.java
> +        String infoText = "";
toto je skor optimalizacna vec, ktora sa vyskytuje hore dole po Fidentise, a treba ju ujednotit, ale ked budes mat cas, skus zmenit "string + string" na pouzitie triedy StringBuilder (vytvara menej objektov)

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkActionDialogueTopComponent.java
> +        List<FpModel> newTmp = CSVparser.load("C:\\Rasto\\School\\Bakalarka\\default.csv");
toto podla mna nebude fungovat

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkActionDialogueTopComponent.java
> +        p.setProperty("version", "1.0");
?

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkActionDialogueTopComponent.java
> +        String version = p.getProperty("version");
? nejaky dovod preco to tu je?

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkTrainDialogueTopComponent.java
> +        //setToolTipText(Bundle.HINT_LandmarkTrainDialogueTopComponent());
znova odstranit zakomentovany kod, dat komponentom nejaky rozumny nazov

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkTrainDialogueTopComponent.java
> +    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
odstran event handling, pokial sa v nom aj tak nic nedeje

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkTrainDialogueTopComponent.java
> +        String filePath = "C:\\Rasto\\School\\Bakalarka\\tmpFidentis\\" + jTextField1.getText() + ".csv";
toto nebude fungovat

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkTrainDialogueTopComponent.java
> +    void readProperties(java.util.Properties p) {
su writeProperties a readProperties metody ktore musia byt implementovane?

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/LandmarkTrainDialogueTopComponent.java
> +    public FpModel trainigModel(List<FpModel> trainingShapes) {
vnutorne citim, ze tato metoda by mala byt v triede, ktora sa zaobera vypoctami a nie GUI

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/Landmarks.java
> +@ActionReference(path = "Menu/File", position = -100)
bolo by vhodnejsie, ak by tato moznost bola v Menu/Landmarks

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisAction.java
> +@ActionReference(path = "Menu/Analysis", position = -100)
bolo by lepsie ak by tato moznost bola v Menu/Landmarks

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisActionDialogue.java
> +        // TODO add your handling code here:
odstran event handling

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisActionDialogue.java
> +    void readProperties(java.util.Properties p) {
writeProperties/readProperties, robia v podstate nic

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisActionDialogue.java
> +    private void addFilesHandler(List<FpModel> fpPoints, List<FpModel> selected, javax.swing.JList<String> jList){
je toto rovnaka metoda ako v triede LandmarkTrainDialogueTopComponent.java? ak ano, dalo by sa to refaktorovat do vlastnej triedy, nech to tu nie je 2x?

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisResults.java
> +      //  final CategoryAxis xAxis = new CategoryAxis("Type");
odstran zakomentovany kod

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisResults.java
> +        panel.setDismissDelay(9999999);
?

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisResults.java
> +    void readProperties(java.util.Properties p) {
read/writeProperties nic nerobia, zmazat

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisResults.java
> +    private String computeFp(int index) {
toto tiez znie, ako by nemalo byt definovane v triede na GUI, ale v triede pre vypocty

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisResults.java
> +                    helpCounter++;
tu pravepodobne staci boolean miesto intu ze?

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisResults.java
> +    private List<Double> computeDistances(List<FacialPoint> one, List<FacialPoint> two, int index) {
tato metoda by mala byt v triede pre vypocty, nie v triede pre GUI

2017-10-09 14:40 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisResults.java
> +            if (index == 0) {
mozno by nebolo od veci skusit enum namiesto int

2017-11-07 10:06 UTC, ZueFe requested changes
este par mensich zmien, plus necommituj depth_image subor

2017-11-07 10:06 UTC, ZueFe commented on Comparison/src/cz/fidentis/comparison/icp/KdTree.java
> +package cz.fidentis.comparison.icp;
Tato trieda sa nachadza v packagy cz.fidentis.comparison.kdTree, pouzij danu implementaciu

2017-11-07 10:06 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/landmarks/Landmark.java
> +    }
Landmark nie je uplne najstastnejsi nazov triedy. Hod tam skor nieco ako PDM, alebo LandmarkTraining

2017-11-07 10:06 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/landmarks/Landmark.java
> +    public static FpModel trainigModel(List<FpModel> trainingShapes, JProgressBar progressBar) {
Vyhod prosimta zavyslost na JProgressBar, updatuj progress bar len pred zacatim treningu a po zacati, alebo rozdel metodu na viacej casti, ktore sa budu volat postupne, aby si mohol progress bar updatovat

2017-11-07 10:06 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/landmarks/Methods.java
> +public enum Methods {
tiez len trochu viac deskriptivny nazov, trieda Methods uz existuje inde, co tak FPAnalysisMethods?

2017-11-07 10:06 UTC, ZueFe commented on Comparison/src/cz/fidentis/comparison/icp/KdTree.java
> +package cz.fidentis.comparison.icp;
Tato trieda sa uz vyskytuje v packagy cz.fidentis.comparison.kdTree, pouzij dany interface

2017-11-07 10:06 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/landmarks/Landmark.java
> +public class Landmark {
To nie je uplne najstastnejsi nazov, skus skor nieco ako PDM, alebo LandmarkTraining

2017-11-07 10:06 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/landmarks/Landmark.java
> +    public static FpModel trainigModel(List<FpModel> trainingShapes, JProgressBar progressBar) {
Odstran zavyslost na JProgressBar, bud rozdel metodu na viacej casti a updatuj progress bar mimo tejto metody, alebo updatni bar len na zaciatku a konci trenovania. Pokial chces pouzivat staticku metodu, sprav z triedy singelton, nech sa nemusi vzdy vytvarat nova trieda.

2017-11-07 10:06 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/landmarks/Methods.java
> +public enum Methods {
trieda Methods uz existuje v inom packagy bolo byt fajn zmenit nazov tak, aby bolo jasne, o metody coho sa jedna (FpAnalysisMethods?)

2017-11-07 10:06 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/Landmarks.java
> +import cz.fidentis.featurepoints.FpModel;
Zas raz len nazov triedy by mohol byt viac popisny (LandmarkAnalysisWindow?)

2017-11-07 10:06 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/actions/analysis/AnalysisActionDialogue.java
>      private static final String[] FP_EXTENSIONS = new String[]{"pp", "PP", "fp", "FP", "csv", "CSV", "pts", "PTS", "dta", "DTA"};
nejak rychlym prehladavanim nevidim, kde sa tato konstanta pouziva?

2017-11-07 10:06 UTC, ZueFe commented on GUI/src/cz/fidentis/gui/observer/ProgressHandleMaster.java
> +public class ProgressHandleMaster {
Tato trieda ja zhodna s triedou ObservableMaster, mozes ju vymazat

2017-11-07 10:06 UTC, ZueFe commented on Processing/src/cz/fidentis/processing/comparison/surfaceComparison/BatchComparisonNumericCallable.java
> +public class BatchComparisonNumericCallable implements Callable<ArrayList<Float>> {
Toto by sa asi tiez nemalo pridavat v commite

2017-11-07 10:06 UTC, ZueFe commented on Processing/src/cz/fidentis/processing/comparison/surfaceComparison/BatchComparisonVisualCallable.java
> +public class BatchComparisonVisualCallable implements Callable<ArrayList<Float>>{
vymaz danu triedu

2017-11-07 10:06 UTC, ZueFe commented on Renderer/src/cz/fidentis/renderer/shaders/ColormapMinMaxFS.glsl
> +#version 420 compatibility
necommituj tento subor

2017-11-07 10:06 UTC, ZueFe commented on Utils/src/cz/fidentis/utils/LandmarkUtils.java
> +public class LandmarkUtils {
len aby si si bol vedomi, toto nebude fungovat, ak bude analyz viac...just btw. Vacsinou, pokial mas nejake atributy triedy (notIn), trieda ma vnutorny stav. Taketo triedy by nemali byt static, uz len kvoli tomu, ze v notIn ti mozu ostat data z predchadzajucej analyzy.

2018-02-05 11:03 UTC, ZueFe requested changes

2018-02-05 11:03 UTC, ZueFe commented on Comparison/src/cz/fidentis/comparison/procrustes/ProcrustesAnalysis.java
> +        List<Integer> cor2 = getFPtypeCorrespondence(this);
preco vytvaras korespondenciu medzi rovnakou konfiguraciou? Pokial ju potrebujes ako List<int>, tak rovno ziskaj zoznam klucov z premennej config, bude to rychlejsie a bude to davat vacsi zmysel

2018-02-05 11:03 UTC, ZueFe commented on Comparison/src/cz/fidentis/comparison/procrustes/ProcrustesAnalysis.java
> +    public ICPTransformation rotatePDM(ProcrustesAnalysis pa2) {
tato metoda je v podstate to iste ako metoda rotate az na mensie zmeny, je mozne obe metody refaktorovat tak, aby tu nebol duplikovany kod? v pripade ze nastane zmena v metode rotate, bude ju potrebne opravovat na 2 miestach, co je zle

2018-02-05 11:03 UTC, ZueFe commented on Comparison/src/cz/fidentis/comparison/procrustes/ProcrustesAnalysis.java
> +        List<ICPTransformation> trans = this.superimposePDM(config2, scaling);
?? nerozbije to celu prokrustovu analyzu? ta metoda sa pouziva aj mimo vyhladavania landmarkov.

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/FeaturePointsUniverse.java
> +        return thresArea.findNoseTip2(thresholdFaces, notUsed);
to bol len docasny nazov, premenuj to prosimta na findAllNoseTipAreas alebo nieco podobne. Tiez samotnu metodu bude treba refaktorovat, kvoli duplikacii kodu

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/ThresholdArea.java
> +    public Set<Set<Integer>> findNoseTip2(Set<Integer> thresholdFaces, boolean notUsed) {
premenovat, refaktorovat metodu findNoseTip tak, aby vyuzivala metodu findNoseTip2

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/AreasSearch.java
> +        for (Integer k : theArea) {
daj mi do tejto metody a do metody na vyhladavanie spicky nosa TODO na refaktor

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/AreasSearch.java
> +    private double sphereDistancePoints(Vector3f point1, Vector3f point2) {
pouzit z modulu Utils, trieda MathUtils

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/AreasSearch.java
> +    private Set<Set<Integer>> findAreas(Set<Integer> vertices, CornerTable ct, boolean discardBoundries, int minAreaSize) {
nie je tato metoda uz v corner table, alebo niekde co si implementoval vyhladavanie oblasti? ked tak ju nahrad, bola tu prekopirovana len kvoli testovaniu

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/AreasSearch.java
> +    private Set<Integer> addToArea(CornerTable ct, int neighbor, Set<Integer> area, Set<Integer> usedIndices, Set<Integer> vertices) {
podobne ako predchadzajuca metoda

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/CSVparser.java
> +package cz.fidentis.featurepoints.pdm;
preco je to tu? je to to iste ako parser, ktory uz vo Fidentise je? Ak ano, tak uprav/pouzij ten, ak nie, tak daj tento parser tam, kde su ostatne parsre z Fidentisu

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/CSVparsers.java
> +package cz.fidentis.featurepoints.pdm;
podobne ako FeaturePoints/src/cz/fidentis/featurepoints/pdm/CSVparser.java, duplikovany kod, opravit

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/CSVparsers.java
> +    public static List<FpModel> load2(String filePath) {
nazvy metod by mohli aspon trocha odzrkadlovat, co metoda robi, napr ako sa lisi od metody load a load3

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/TrainingModel.java
> +    public double distancePoints(Vector3f point1, Vector3f point2) {
naprogramovane v module Util, MathUtils, pouzit odtial

2018-02-05 11:03 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/TrainingModel.java
> +    private void quickSort(int lowerIndex, int higherIndex) {
na sortovanie tiez existuje v module Utils trieda, prehod to prosimta tam, ak to pojde, urcite sa to zide aj inde

2018-02-05 11:03 UTC, ZueFe commented on Processing/src/cz/fidentis/processing/featurePoints/FpProcessing.java
> +        ///////
prihod TODO na refaktor k povodnej metoda vyhladavania landmarkov pre jednu tvar v pripade ze ju neodstranujes

2018-02-05 11:03 UTC, ZueFe commented on Processing/src/cz/fidentis/processing/featurePoints/FpProcessing.java
> +        JFileChooser fileChooser = new JFileChooser();
?? toto uz je vyhladavanie landarkov, preco sa tu vybearju nejake subory? nemali byt uz vybrane?

2018-02-05 11:03 UTC, ZueFe commented on Processing/src/cz/fidentis/processing/featurePoints/LandmarkLocalization.java
> +        TrainingModel train = new TrainingModel();
netrenuj novy model pri kazdom vyhladavani, model by uz mal byt natrenovany a vyuzivat by sa mal ten, ktory je vybrany v programe

2018-02-05 11:03 UTC, ZueFe commented on Processing/src/cz/fidentis/processing/featurePoints/LandmarkLocalization.java
> +    public List<FacialPoint> makeArea(Model model, File[] trainingShapesFiles) {
lepsi nazov metody, make area mi nijak neevokuje co sa v metode deje (co to ma spolocne s trenovanim modelu, alebo vyhladavanim landmarkov?)

2018-02-20 17:23 UTC, RastislavStefanko commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/AreasSearch.java
> +    private Set<Set<Integer>> findAreas(Set<Integer> vertices, CornerTable ct, boolean discardBoundries, int minAreaSize) {
Neviem ju najst :(

2018-02-21 12:14 UTC, ZueFe commented on FeaturePoints/src/cz/fidentis/featurepoints/pdm/AreasSearch.java
> +    private Set<Set<Integer>> findAreas(Set<Integer> vertices, CornerTable ct, boolean discardBoundries, int minAreaSize) {
ked nie tak nie :)

2018-06-26 13:09 UTC, ZueFe commented
moved to https://github.com/Fidentis/Analyst/pull/56

2018-06-26 13:09 UTC, closed without merging